version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/Mediporta.Api/Dockerfile
    container_name: mediporta.api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: mediporta.db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: stackexchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:


